sudo: required

git:
  depth: 10

language: node_js

node_js: 6

script: npm run test:noasmjs

notifications:
  email:
    on_success: never
    on_failure: change

env:
  - CXX=clang++-3.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - gcc-5
      - g++-5
      - clang-3.8
